### PR TITLE
Sort the list of flags by alphabetical order

### LINKED ISSUE #533: Flag missorted in list
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Go to Languages / Languages
2. Search the United Kingdom flag
3. United Kingdom seems to be alphabetically between Galicia and Grenada :-)

## Expected behavior and actual behavior

This flag should be listed in the "U" or renamed "Great Britain"
gb

### PR DESCRIPTION
**Pull request by Chouby**
Closes #533

This PR uses [`Collator`](https://www.php.net/manual/en/class.collator.php) to sort the flags by alphabetical order (depending on the user locale). I did not implement a locale conversion as the WordPress locale should be correctly interpreted in most cases.
If we have complaints that the order is crazy in some locales which could not be correctly interpreted, we may introduce a conversion in a second time.

If the `intl` extension is not present, then I fallback to standard sort (which will work correctly for English).

### CODE REVIEW

File: src/settings/settings.php [hunk 1]
```diff
@@ -408,4 +410,26 @@ public static function get_predefined_languages() {
...
+		if ( class_exists( 'Collator' ) ) {
+			$co = Collator::create( get_user_locale() );
+			if ( $co ) {
+				$co->asort( $flags );
+				return $flags;
+			}
+		}
+
+		asort( $flags );
+		return $flags;
```
Comment (Screenfeed) [inline src/settings/settings.php]: I would reverse the logic, so we don't pile up 2 `if`:


```suggestion
		if ( ! class_exists( 'Collator' ) ) {
			asort( $flags );
			return $flags;
		}

		$co = Collator::create( get_user_locale() );
		if ( $co ) {
			$co->asort( $flags );
		}

		return $flags;
```

What do you think?

**Review by Screenfeed — CHANGES_REQUESTED** [review]

**Review by Screenfeed — APPROVED** [review]
