### PR TITLE
Fix conflict with Yoast Duplicate Post

### LINKED ISSUE #1536: Pro: Yoast SEO Rewrite & Republish on Synched Translations deletes the post
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

This issue is unrelated to #813.

## Steps to reproduce the issue

1. Setup a clean WordPress with Polylang Pro and Duplicate Posts (by Yoast) installed.
2. Make sure at least two langauges are available.
3. Create a new post with a synched translation.
4. Use the "Rewrite & Republish" feature of Duplicate Posts on your new post.
5. "Republish" your new Post Draft.

## Expected behavior and actual behavior

Due to the synchronisation of the posts, all of the Duplicate Posts related meta data is copied from the new draft back to the original post. This leads to a fatal behaviour when executing "Republish" – Duplicate Posts replaces the original post with the Draft (which is expected behaviour) but then continues to delete the old draft _and_ the original post as well, since the meta data marks it as a duplicate of itself.

This can be observed also by deleting the draft instead of republishing it. Upon page reload you can see that the original post is labeled as "Rewrite & Republish" of _itself_ in the list.

I don't know if excluding all the Duplicate Post metadata from the translation process would be enough to fix this problem.

In `polylang-pro/vendor/wpsyntex/polylang/integrations/duplicate-post/duplicate-post.php`:

```php
add_filter( 'pll_copy_post_metas', 'exclude_duplicate_post_meta' );

function exclude_duplicate_post_meta( array $keys ) {
    $keys_to_remove = [
         "_dp_original",
         "_dp_is_rewrite_republish_copy",
         "_dp_has_rewrite_republish_copy",
         "_dp_creation_date_gmt"
    ];

    return array_diff( $keys, $keys_to_remove );
}
```

Alternatively, the function "Rewrite & Republish" should be disabled or come with a warning in conjunction with synched translations in Polylang Pro. Unexpected post deletion is a big problem a client of us had in their production environment due to this bug.

### PR DESCRIPTION
**Pull request by Chouby**
Fix #1536 

Fix synchronized posts deleted when using "Rewrite & Republish" by excluding post metas from the copy/synchronizations as suggested.

Also fixes the broken translations group when a post is republished.
To reproduce :
1. Create 2 translated posts (not necessarily synchronized), Let say English and French.
2. In the list table click on "Rewrite & Republish", let say for the English post. 
3. Once the editor is open, click on Republish.
4. Visit the posts list table and see how the French post has lost its link to the English post. 
image

To fix the issue, I had to partially revert a28f803d0a79ee6e0c535060cd7978e8b741a776. Indeed Duplicate Post breaks the translations group, but it's not possible to repair it (seen from the English post, the translations look ok, so if we attempted to repair it `should_update_translation_group()` would return false). So need to always update the translation group if we want to be able to repair it (I excluded only one case for terms when the translation group only includes one term). See [the test](https://github.com/polylang/polylang/blob/3.8.2/tests/phpunit/tests/test-translated-term.php#L223) which pushed me to exclude this specific case.

### CODE REVIEW

**Review by Screenfeed — CHANGES_REQUESTED** [review]
Sadly this doesn't solve the issue entirely.

If 2 posts are synced and we use "Rewrite & Republish", it breaks the synchronization group. This can be seen in 2 ways:
1. when republishing: we can see that the sync group is broken when we visit the edit page of the translation (the field is empty).
2. when drafting the "republished" post: the synced post is also drafted and it becomes a copy of the republished post.

**Comment by Chouby** [comment]
See the updated description.

File: src/integrations/duplicate-post/duplicate-post.php [hunk 1]
```diff
@@ -34,4 +37,42 @@ public function taxonomies_blacklist( $taxonomies ) {
...
+	 * Exclude Duplicate Post metas from the copy/synchronization.
+	 *
+	 * This avoids synchronized posts to be deleted when using "Rewrite & Republish".
+	 *
+	 * @since 3.9
+	 *
+	 * @param string[] $keys List of meta keys.
+	 * @return string[]
+	 */
+	public function exclude_post_metas( $keys ) {
```
Comment (Screenfeed) [inline src/integrations/duplicate-post/duplicate-post.php]:
```suggestion
	public function exclude_post_metas( $keys ): array {
```

File: src/integrations/duplicate-post/duplicate-post.php [hunk 2]
```diff
@@ -34,4 +37,42 @@ public function taxonomies_blacklist( $taxonomies ) {
...
+	/**
+	 * Fixes the translations group just after a post is republished.
+	 *
+	 * @since 3.9
+	 *
+	 * @param int $copy_id The copy's ID.
+	 * @param int $post_id The original post's ID.
+	 * @return void
+	 */
+	public function after_rewriting( $copy_id, $post_id ) {
```
Comment (Screenfeed) [inline src/integrations/duplicate-post/duplicate-post.php]:
```suggestion
	public function after_rewriting( $copy_id, $post_id ): void {
```

**Review by Screenfeed — CHANGES_REQUESTED** [review]

**Review by Screenfeed — APPROVED** [review]

**Comment by intelligence** [comment]
Is this slated for the next release?

**Comment by Screenfeed** [comment]
It is scheduled for the version 3.9.
