### PR TITLE
Restore current language management in multisite.

### LINKED ISSUE #1452: pll_get_post() after switching to another blog.
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install a WordPress site
2. Configure this site as a network site.
3. Create 2 sites
4. Create a page in the both sites.
6. In one of the sites, try to get the translated id of a page of the other site using `switch_to_blog($blog_id)`and `pll_get_post($page_id)`.

## Expected behavior and actual behavior
I should get the translated id of the page but I get `false`.

----

## Code example
```php
switch_to_blog(1); // 1 = ID of parent site
    $id_of_page_in_parent_site = function_exists('pll_get_post') ? pll_get_post(5) : 5; // Returns false in 3.6 BUT returns 5 in 3.5.4
    echo get_field( 'global_title', $id_of_page_in_parent_site );
restore_current_blog();
```

## Proposition of fix that works for me
I have changed the content of the function set in the file cache.php (vendor/wpsyntex/polylang/include/cache.php:66):
```php
public function set( $key, $data ) {
    // Before:
    // if ( ! doing_action( 'switch_blog' ) ) {
    //  $this->cache[ $this->blog_id ][ $key ] = $data;
    // }
    // return $data;

    // After:
    $this->cache[ $this->blog_id ][ $key ] = $data;
    return $data;
}
```

### LINKED ISSUE #1455: PHP Fatal Error Due to Memory Exhaustion After Plugin Update
Dear Support Team,

I hope this message finds you well. I am writing to report a critical issue I've encountered with Polylang after its recent update (3.6). Upon updating the plugin, my website started experiencing a fatal error which halted its operation. The specific error encountered is as follows:

**PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 266240 bytes)**

Troubleshooting Attempts:

* I have tried increasing the PHP memory limit to 1GB, which is substantial, but the issue persists.
* Downgrading to the previous version is  3.5.3 of the plugin resolves the error, indicating that the issue is specific to the latest update.

I kindly request your assistance in resolving this issue. It's critical for the continued operation of my website to either have a fix for the current version or guidance on any settings I may adjust to prevent this error. If additional information or access is required to diagnose this problem, please let me know, and I'll provide it promptly.

Thank you for your attention to this matter. I look forward to your swift response and a resolution to this issue.

**CURRENT PHP VERSION : 7.4**
**DOWNGRADE PLUGIN VERSION: 3.5.3**
**LATEST PLUGIN VERSION (ERROR) : 3.6**

Best regards,
Tanjil Ahmed

### PR DESCRIPTION
**Pull request by Hug0-Drelon**
## What?
Fixes #1455 
Fixes #1452 

Current language has been lost during `switch_to_blog()` since #1415. This is because languages data is not cached anymore, thus current language has to be recalculated each time a function needing it is called (leading to infinite loop in specific cases, `get_home_url()` for instance).

## How?
- Revert #1415.
- Still fix what #1415 was fixing by skipping cache for translated CPT and taxonomies during `switch_blog`.
- Add tests, unfortunately I didn't manage to reproduce the infinite loop with `get_home_url()` in these tests...

### CODE REVIEW

File: tests/phpunit/tests/test-switch-blog-custom-code.php [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+			$this->assertNotEmpty( $home );
+
+			$this->assertInstanceOf( PLL_Language::class, $pll_frontend->curlang );
+
+			$post_id = pll_get_post( $this->posts[ (int) $this->blog_with_pll_directory->blog_id ]->ID );
+
+			$this->assertNotFalse( $post_id );
+			$this->assertSame( $this->posts[ (int) $this->blog_with_pll_directory->blog_id ]->ID, $post_id );
+
+			restore_current_blog();
```
Comment (Screenfeed) [inline tests/phpunit/tests/test-switch-blog-custom-code.php:66]: I think this could go in a `foreach` loop:
```php
$blogs = array( 'blog_with_pll_directory', 'blog_with_pll_domains', 'blog_with_pll_plain_links' );

foreach ( $blogs as $blog ) {
    switch_to_blog( (int) $this->{$blog}->blog_id );
    ...
}

$blogs = array( 'blog_without_pll_pretty_links', 'blog_without_pll_plain_links' );

foreach ( $blogs as $blog ) {
    switch_to_blog( (int) $this->{$blog}->blog_id );
    ...
}
```

What do you think? It could reduce the test's length.

File: tests/phpunit/tests/test-switch-blog-custom-code.php [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+			$this->assertNotEmpty( $home );
+
+			// Even though Polylang is deactivated on the current blog, the current language must be kept.
+			$this->assertInstanceOf( PLL_Language::class, $pll_frontend->curlang );
+
+			$post_id = pll_get_post( $this->posts[ (int) $this->blog_without_pll_pretty_links->blog_id ]->ID );
+
+			$this->assertNotFalse( $post_id );
+			// No language, no post.
+			$this->assertSame( 0, $post_id );
```
Comment (Screenfeed) [inline tests/phpunit/tests/test-switch-blog-custom-code.php:120]: `assertNotFalse()` isn't necessary then.

**Review by Screenfeed — CHANGES_REQUESTED** [review]

File: tests/phpunit/tests/test-switch-blog-custom-code.php [hunk 3]
```diff
@@ -0,0 +1,145 @@
...
+						$languages[0]['slug'] => $post->ID,
+						$languages[1]['slug'] => $tr_post->ID,
+					)
+				);
+			}
+		}
+
+		public function test_switch_blog_with_custom_code() {
+			$pll_frontend = $this->get_pll_frontend_env();
+			$pll_frontend->curlang = $pll_frontend->model->get_language( 'en' ); // English is a common language for blogs with Polylang activated, @see {PLL_Multisites_TestCase::set_up()}.
```
[the remark this answers is not in the document]
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php:45]: Not at all. 
I needed a common language across blogs, and given that I've coded `PLL_Multisites_TestCase` I know English is fitting. So I added a comment for clarity, meaning I didn't chose a random language.
Also, I wouldn't trust a LLM for multisite related code.

[the remark this answers is not in the document]
Comment (Screenfeed) [reply tests/phpunit/tests/test-switch-blog-custom-code.php:45]: > Also, I wouldn't trust a LLM for multisite related code.

I wouldn't even trust a human 😏

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 2 above)
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php:120]: Well I do want to test the result isn't `false`, because it doesn't mean the same as `0`.
I the result is `false`, it means the current language has been lost.

File: tests/phpunit/tests/test-switch-blog-custom-code.php [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+		 *
+		 * @param WP_Site        $blog      Current site object.
+		 * @param PLL_Admin|null $pll_admin Polylang admin object, null if deactivated.
+		 * @param array          $languages Array of blog languages data, empty if none.
+		 * @return void
+		 */
+		protected function create_fixtures_for_blog( WP_Site $blog, $pll_admin = null, array $languages = array() ) {
+			$post = $this->factory()->post->create_and_get();
+
+			$this->posts[ (int) $blog->blog_id ] = $post;
```
[the remark this answers is not in the document]
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: 🧙

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (Screenfeed) [reply tests/phpunit/tests/test-switch-blog-custom-code.php:46]: To clarify my 1st comment, it was a joke because the sentence "English is a common language for blogs with Polylang activated" sounded like it comes from statistics about sites that use Polylang (in general, out of the context of this test) 😅

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: Removed in 10a0a12c.

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 1 above)
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: Good idea, added in 10a0a12c.

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 2 above)
Comment (Screenfeed) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: You already test it's not `false` with `assertSame()` since it does a strict comparison. Or am I wrong?

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php:46]: I see 🤣 
I admit it sounds a bit artificial^^

File: tests/phpunit/tests/test-switch-blog-custom-code.php (hunk 2 above)
Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: Well, I'm stupid...

Comment (Hug0-Drelon) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: Removed in 6fc67034.

Comment (Screenfeed) [reply tests/phpunit/tests/test-switch-blog-custom-code.php]: Homer Boo Boo

**Review by Screenfeed — APPROVED** [review]
