### PR TITLE
Browser preferred language update

### LINKED ISSUE #591: Wrong language detection with Accept-Language: zh-Hant-HK
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add `en`, `zh` and `zh_HK` languages to WP site with `en` being the default.
2. Set active Windows 10 UI language to "Chinese (Hong Kong)".
3. Open the site on Edge (old).

## Expected behavior and actual behavior

Expected: It should redirect to the `zh_HK` homepage.

Actual: It redirects to the `zh` homepage instead.

## Additional information

The `Accept-Language` header sent by Edge is `zh-Hant-HK, zh-Hant; q=0.8, en-US; q=0.6, en; q=0.4, ja; q=0.2` (I have multiple UI languages installed). It is obvious that the site picked up on the `zh` part because it chose `zh` over `en`, but failed to pick up on the `HK` region tag possibly due to the presence of the `Hant` script tag.

P.S. This is on Win 10 version 1909 (build 18363.1082) and old Edge 44.18362.449.0. On my other system with Windows 10 version 1903 (build 18362.1082) and the same Edge verion, the `Accept-Language` header is simply `zh-HK` and so does not show the issue.

The detection behaviour can be more directly tested by using `curl` on a Linux terminal, Git Bash can also work (replace URL with test site):

```
$ curl http://example.com/ -s -D - -o /dev/null | grep -i location:
location: http://example.com/en/

$ curl -H "Accept-Language: zh-HK" http://example.com/ -s -D - -o /dev/null | grep -i location:
location: http://example.com/zh-hk/

$ curl -H "Accept-Language: zh-Hant-HK" http://example.com/ -s -D - -o /dev/null | grep -i location:
location: http://example.com/zh/
```

### PR DESCRIPTION
**Pull request by raaaahman**
## Before

Our Browser Preferred Language detection could only work with language and region information transmitted from WordPress visitors' browser agents, like 'en-GB' or 'zh-CN'.

It used to detect incomplete matches where either the 'language' or 'region' information matched one of the languages sent in the Accept-Language HTTP Header, given that the websites used **only one tag** in their slugs, like 'gb' or 'zh'.

Fixes #591

## Changes

- Updates 'Accept-Language' HTTP Header parsing to be compatible with [BCP 47](https://tools.ietf.org/html/bcp47#section-2.1)
- Allows our detection to match website's languages with close Accept-Languages values, including:
  - A 'language' only match
  - A 'language-region' match
  - A 'region' only match
  - A 'language-variant' match
 - Improve consistency of Preferred Language detection with custom slugs.

## Going further

Should we only match languages that are set as 'actives' when used in Polylang Pro?

### CODE REVIEW

**Review by Marianne380 — APPROVED** [review]

File: frontend/choose-lang.php [hunk 1]
```diff
@@ -130,50 +138,14 @@ public function maybe_setcookie() {
...
+		$accept_langs = new PLL_Accept_Languages_Collection();
 
 		if ( isset( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) ) {
-			// Break up string into pieces ( languages and q factors )
-			preg_match_all(
-				'/([a-z]{1,8}(-[a-z]{1,8})?)\s*(;\s*q\s*=\s*((?>1|0)(?>\.[0-9]+)?))?/i',
-				sanitize_text_field( wp_unslash( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) ),
-				$lang_parse
-			);
+			$accept_langs = PLL_Accept_Languages_Collection::from_accept_language_header( sanitize_text_field( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) );
```
Comment (Chouby) [inline frontend/choose-lang.php:144]: Add `wp_unslash()`.

**Review by Chouby — CHANGES_REQUESTED** [review]

**Comment by alvinhochun** [comment]
Hi, thanks for making the changes to fix the issue. I believe our site currently has Polylang 3.0.6 installed, however which should include the changes here, but for some reason `zh-Hant-HK` in accept-language still redirects me to the `zh_CN` version of the site, any idea on how it could be happening?

This is our language settings:
圖片


```console
$ curl -H "Accept-Language: zh-Hant-HK" https://krita.org/ -s -D - -o /dev/null | grep -i location:
location: https://krita.org/zh/

$ curl -H "Accept-Language: zh-HK" https://krita.org/ -s -D - -o /dev/null | grep -i location:
location: https://krita.org/zh-hk/
```

**Comment by raaaahman** [comment]
Indeed, the results seems to be dependent on the order in which the languages are queried from the database:

https://github.com/polylang/polylang/blob/ce90849b24b459b4d0589a215b2b2eae75cf900d/frontend/accept-languages-collection.php#L138

We should perform a 'weighted comparison' instead. Example: matching language is worth 1000, matching region 100, matching script 10, etc. And the highest value is returned.
